app/routes.php
<?php
Route::get ( '/', array (
'as' => 'home',
'uses' => 'HomeController@home'
		) );
/*
 * Authentication group
 */
Route::group(array('before'=>'auth', 'namespace' => 'Admin'), function (){
	Route::group ( array ('before' => 'csrf'), function () {	
		
		
	/*
	 * Use for product action
	 */
	Route::post('admin/product-update/{id}', array(
		'as'=>'product-update',
		'uses'=>'ProductController@updateProduct'
	));
	
	Route::post('admin/prduct-manager/product-addnew', array(
				'as'=>'addnew-product',
				'uses'=>'ProductController@addnewProduct'
	));
	
	Route::post('admin/product-manager/addnew', array(
			'as'=>'post-product-addnew',
			'uses'=>'ProductController@insertProduct'
	));
	
	/////////////////////////////////////////////////////////////////////
});
	
	
/////////    Get all method for product action /////////////////////////
Route::get('admin/product-manager', array(
		'as'=>'product-manager',
		'uses'=>'ProductController@listProduct'
));

Route::get('admin/product-manager/addnew', array(
			'as'=>'get-addnew-product',
			'uses'=>'ProductController@addnewProduct'
));
Route::get('admin/product-manager/delete/{id}', array(
			'as'=>'get-delete-product',
			'uses'=>'ProductController@removeProduct'
));
Route::get('admin/product-manager/edit/{id}',array(
			'as'=>'get-edit-product',
			'uses'=>'ProductController@editProduct'
));

///////  End for product  ////////////////////////////////////

/// Admin logout /////////////////
Route::get('/admin/admin-logout', array(
		'as'=>'admin-logout',
		'uses'=>'AccountController@getLogOut'
	));
});



/*
 * Unauthenticated group
 */
Route::group ( array ('before' => 'guest' ,'namespace' => 'Admin'), function () {
	/*
	 * CSRF protection
	 */
	Route::group ( array ('before' => 'csrf' ), function () {
		Route::post('admin/admin-login', array(
			'as'=>'post-admin-login',
			'uses'=>'AccountController@postLogin'
		));
	} );
	
	/*
	 * Signin (GET)
	 */
		Route::get('admin/admin-login', array(
		'as'=>'get-admin-login',
		'uses'=>'AccountController@getLogin'
		));


} );

Route::get('/add-item-tocart/{id}', array(
		'as'=> 'addToCart',
		'uses'=>'HomeController@addCart'
	));


Route::resource('Test', 'TestController');


Route::resource('orders', 'OrdersController');

Route::resource('students', 'StudentsController');

Route::resource('lops', 'LopsController');

Route::resource('admin/computers', 'ComputerController'); // admin

app/views/admin/addnew.blade.php
@extends('admin.main')
@section('content')
	{{Form::open(array('route'=>'admin.computers.store', 'files'=>true))}}
		<div>
			{{Form::label('lblName', 'Name')}}
			{{Form::text('name')}}
		</div>
		<div>
			{{Form::label('lblPrice', 'Price')}}
			{{Form::text('price')}}
		</div>
		<div>
			{{Form::label('lblweight', 'Weight')}}
			{{Form::text('weight')}}
		</div>
		<div>
			{{Form::label('lbdate', 'Date')}}
			{{Form::text('date_manufacture')}}
		</div>
				<div>
			{{Form::label('lblMaker', 'Maker')}}
			{{Form::select('conputer_maker_id',$maker)}}
		</div>
		<div>
			{{Form::file('image')}}
		</div>
		<div>
			{{Form::submit('Insert')}}
		</div>
		
	{{Form::close()}}
@stop

app/views/admin/editProduct.blade.php
@extends('admin.main')
@section('content')
	{{Form::model([$maker, $product],array('method' => 'PATCH', 'route' => array('admin.computers.update', $product->id), 'files'=>true))}}
		<div>
			{{Form::label('lblName', 'Name')}}
			{{Form::text('name', $product->name)}}
		</div>
		<div>
			{{Form::label('lblPrice', 'Price')}}
			{{Form::text('price',  $product->price)}}
		</div>
		<div>
			{{Form::label('lblMaker', 'Maker')}}
			{{Form::select('conputer_maker_id',$maker,  $product->pcmaker->id)}}
		</div>
		<div>
			{{Form::file('image')}}
		</div>
		<div>
			{{Form::submit('Update')}}
		</div>
		
	{{Form::close()}}
@stop

app/views/admin/login.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>ADMIN PAGE</title>
</head>

<body>
<table width="40%" border="0" align="center" bgcolor="#CCCCCC">
	<form action="{{ URL::route('get-admin-login') }}" method="post">
		<tr align="center">
			<td colspan="2">LOGIN ADMIN</td>
		</tr>
		<tr>
			<td>ACCOUNT :</td>
			<td><input type="text" name="username" /></td>
			<td><label name='userError' color="red">
				@if($errors->has('username'))
				{{ $errors->first('username') }}
			@endif		
			</label></td>
		</tr>
		<tr>
			<td>PASSWORD</td>
			<td><input type="password" name="password" /></td>
			<td><label name='passError' color="red">
			@if($errors->has('password'))
				{{ $errors->first('password') }}
			@endif
			</label></td>
		</tr>
		<tr align="center">
			<td><input type="submit" name="btnLogin" value="Signin" /></td>
			<td><input type="reset" name="nhaplai" value="reset" /></td>
			<td><input type="checkbox" name='remember' >Remember</input></td>
		</tr>
		{{Form::token()}}
	</form>
</table>
</body>
</html>

app/views/admin/main.blade.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<link href="../style/admin.css" rel="stylesheet" type="text/css" />
</head>

<body>
  <div id="id_all">
@include('admin.navigation')
@yield('content')
</div>
</body>
</html>

app/views/admin/navigation.blade.php
<div id="id_top">"
<div id="id_top_dangky">
 Quyền  &nbsp;|&nbsp;<a
		href="index.php" /><a href="{{URL::route('admin-logout')}}"> Đăng xuất</a>

</div>
<div id="id_top_menu">
<ul>
	<li><a href="#">Quản Lý Nhân Viên</a></li>
	<li><a href="#">Quản lý Nhà Cung Cấp</a></li>
	<li><a href="{{route('product-manager')}}">Quản lý Sản Phẩm </a></li>
	<li><a href="#">Quản lý TT Khách hàng </a></li>
	<li><a href="#">Quản lý TT Hoa Don </a></li>
</ul>
</div>

app/views/admin/product.blade.php
@extends('admin.main')
@section('content')
	

    <div align="center" style="margin: 0px auto">
<table width="880" border="1" align="center">
	<caption>
	</caption>
	<tr align="center">
		<td height="38" colspan="7">
		<p style="font-size: 24px"><strong>PRODUCT - MANAGERMENT</strong></p>
		</t>
	</tr>


	<tr align="center">

		<td width="176" colspan="5" align="CENTER">
			INFOMATION
		</td>
		<td>
			ACTION
		</td>
	</tr>

	<tr align="center">
		<th>ID </th>
		<th>NAME</th>
		<th>PRODUCER</th>
		<th>PRICE ($)</th>
		<th> IMAGE</th>
		<th>
			<a href="{{URL::route('admin.computers.create')}}">
				<p style="color: #F4726D; font-size: 18px; background-color: #F0FFF0;">
					<strong>ADD NEW</strong>
				</p>
			</a>
		</th>
	</tr>
 @foreach ($mComputer as $com)
<!--  {{var_dump($com->pcmaker_id);}}
 	{{ $com->pcmaker->name }} 
	nho co relationship nen ta goi duoc ten cua hang san xuat nho ham relationship pcmaker trong Computermodel
 	-->

  <tr align="center">
		<td bgcolor="#FFFFFF" class="style1">{{$com->id}}</td>
		<td bgcolor="#FFFFFF" class="style1">{{$com->name}}</td>
		<td bgcolor="#FFFFFF" class="style1">{{$com->pcmaker->name}}</td>
		<td bgcolor="#FFFFFF" class="style1">{{$com->price}}</td>
		<td bgcolor="#FFFFFF" class="style1"><img width="54" height="36"
			src="../public/image_sp/{{$com->image}}" /></td>
		<td bgcolor="#FFFFFF" class="style1"><a
			href="{{URL::route('admin.computers.edit', $com->id)}}">EDIT</a>&nbsp;|&nbsp;
			{{Form::open(array('method' => 'DELETE', 'route'=>array('admin.computers.destroy', $com->id)))}}
				{{Form::submit('remove')}}
			{{Form::close()}}
			</td>
	</tr>
   @endforeach						
</table>
</div>
@stop